### ISSUE TITLE
The project created from the UWP project template couldn't find any namespace

### ISSUE THREAD

**Issue by womandroid** [brandmooffin/cocos2d-mono#45] opened 2021-04-25 07:16 UTC
I created the project from the Cocos2DMonoGame.Uwp template, but all namespaces are invalid.
For example, I got the error:
> The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
Thanks.

**Comment by brandmooffin** [comment] 2021-04-26 14:16
Thanks for bringing up this issue, I was able to reproduce it. It looks like the project template wasn't packaged correctly. I'll work on a fix for this and will update here once its ready 😄

**Comment by brandmooffin** [comment] 2021-04-29 00:51
A recent fix has been merged and should resolve this issue. Please check out the latest update for [Cocos2D-Mono Project Templates extension](https://marketplace.visualstudio.com/items?itemName=Cocos2D-MonoTeamBrokenWallsStudios.cocos2dmonoprojecttemplates) and give it another try! 

I will be closing this issue for now, please feel free to re-open if the issue still continues. Thanks!

**Closed by brandmooffin** 2021-04-29 00:51 UTC
Labels: bug

**Comment by womandroid** [comment] 2021-04-30 05:14
Thank you for your time. I tried again, but it didn't seem to work. The same errors.

**Comment by brandmooffin** [comment] 2021-05-04 17:56
Sorry I couldn't get back sooner. Let's see if we can figure out what's going on here.

Just to make sure, are you using the template provided from the extension? or did you manually add the template that's provided in this repo? or maybe even both?

I know VS is a little tricky if you are using both the extension and have added the template files manually to the ProjectTemplates directory.

**Comment by womandroid** [comment] 2021-05-05 05:13
I downloaded the template file from the link you gave and installed it via VSIXInstaller.exe before.
Just now, I tried to install it directly from vs Extensions, and now it works fine.
Thanks for your work.
